//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeuPendu
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionnaireTable
    {
        public int id { get; set; }
        public string mot { get; set; }
        public Nullable<int> idLangue { get; set; }
        public Nullable<int> idNiveau { get; set; }
    
        public virtual Langue Langue { get; set; }
        public virtual Niveau Niveau { get; set; }
    }
}
