//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeuPendu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriqueTable
    {
        public int id { get; set; }
        public string mot { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> erreurs { get; set; }
        public Nullable<int> temps { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string reussi { get; set; }
    }
}
